// Mocks generated by Mockito 5.0.8 from annotations
// in free_chat/test/network/networking_test.dart.
// Do not manually edit this file.

import 'package:free_chat/src/fcp/fcp_connection.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [FcpConnection].
///
/// See the documentation for Mockito's code generation for more information.
class MockFcpConnection extends _i1.Mock implements _i2.FcpConnection {
  MockFcpConnection() {
    _i1.throwOnMissingStub(this);
  }
}
